### ISSUE TITLE
The process cannot access the file because another process has locked a portion of the file

### ISSUE THREAD

**Issue by slashlosko** [enayet123/BackupOnEventPlugin#3]
Hi, I'm getting this error in the server console when backuping:
`[20:13:30] [Server thread/INFO]: 1337slash issued server command: /backup
[20:13:38] [Craft Scheduler Thread - 3/INFO]: [BackupOnEvent] Failed to backup world! Please check server logs!
[20:13:38] [Craft Scheduler Thread - 3/WARN]: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.FileDispatcherImpl.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.IOUtil.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.FileChannelImpl.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.ChannelInputStream.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.ChannelInputStream.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at sun.nio.ch.ChannelInputStream.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at java.io.BufferedInputStream.fill(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at java.io.BufferedInputStream.read1(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at java.io.BufferedInputStream.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at java.io.FilterInputStream.read(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at ZipUtil.addDirRecursively(ZipUtil.java:127)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at ZipUtil.createZip(ZipUtil.java:82)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at ZipUtil.ZipDirs(ZipUtil.java:60)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at BackupRunnable.run(BackupRunnable.java:56)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:13:38] [Craft Scheduler Thread - 3/WARN]:   at java.lang.Thread.run(Unknown Source)`

Better logs: https://mclo.gs/li0Is3k

The server's running on Spigot 1.16.1 on a Windows 10 machine.
Java version 8 update 231

What should I do? :(
Thanks!

**Comment by enayet123** [comment]
Hey, are you using the latest version of BackupOnEvent? I released a supposed fix however I wasn’t able to test it. If this bug is still present in BackupOnEvent 1.6.1 would you be able to work with me to create a fix?

**Comment by slashlosko** [comment]
I think I have it, because I downloaded the latest file from the bukkit site.
And what do you mean by working with you to create a fix? Do you need a tester?

**Comment by enayet123** [comment]
@1337slash The bug only seems to occur on windows and I have only got MacOS. If you would be willing to help please let me know

**Comment by slashlosko** [comment]
Yes, sure! What can I do?

**Comment by enayet123** [comment]
Drop me a message on Discord if you have it: Enayet#7631

**Comment by enayet123** [comment]
Resolved in v1.6.2
